debug: true
http:
  port: 8080
listen:
  tcp:
    - addr:
        host: 127.0.0.1
        port: 9000
      allowed: [ '192.168.1.0/24' ]
      concurrency_limit: 10
      max_wait_time: 10
      max_queue_size: 10
  http:
    - host: 127.0.0.1
      port: 8124
      concurrency_limit: 10
      max_wait_time: 10
      max_queue_size: 10
table_lists:
targets: # solve problem with handshake versions - give earlier
  table_groups:
    - &group1
      - 'db.*'
      - 'db.table'
    - &group2
      - 'db.table'
      - 'db.table'
  clusters:
    - host: 127.0.0.1
      port: 9001
      user:
      pass:
      special_tables:
        type: white
        list: [ *group1, *group2 ]
