version: '3.5'
services:
  clickhouse01:
    image: clickhouse/clickhouse-server
    container_name: clickhouse01
    hostname: clickhouse01
    ports:
      - "127.0.0.1:8223:8123"
      - "127.0.0.1:9001:9000"
  #    volumes:
  #      - ${PWD}/var/clickhouse01:/etc/clickhouse-server
